#!/usr/bin/env bash

CONFIG_FILE=/opt/fhir/conf/config.properties

sed -i "s#<DB_URL>#${DB_URL}#" $CONFIG_FILE
sed -i "s#<DB_LIQUIBASE_USER>#${DB_LIQUIBASE_USER}#" $CONFIG_FILE
sed -i "s#<DB_LIQUIBASE_USER_PASSWORD>#${DB_LIQUIBASE_USER_PASSWORD}#" $CONFIG_FILE
sed -i "s#<DB_SERVER_USER_GROUP>#${DB_SERVER_USER_GROUP}#" $CONFIG_FILE
sed -i "s#<DB_SERVER_USER>#${DB_SERVER_USER}#" $CONFIG_FILE
sed -i "s#<DB_SERVER_USER_PASSWORD>#${DB_SERVER_USER_PASSWORD}#" $CONFIG_FILE
sed -i "s#<CORS_ORIGINS>#${CORS_ORIGINS}#" $CONFIG_FILE
sed -i "s#<ORGANIZATION_IDENTIFIER>#${ORGANIZATION_IDENTIFIER}#" $CONFIG_FILE
sed -i "s#<ORGANIZATION_TYPE>#${ORGANIZATION_TYPE}#" $CONFIG_FILE
sed -i "s#<WEBSERVICE_BASE_URL>#${WEBSERVICE_BASE_URL}#" $CONFIG_FILE
sed -i "s#<WEBSERVICE_P12_CERTIFICATE>#${WEBSERVICE_P12_CERTIFICATE}#" $CONFIG_FILE
sed -i "s#<WEBSERVICE_P12_CERTIFICATE_PASSWORD>#${WEBSERVICE_P12_CERTIFICATE_PASSWORD}#" $CONFIG_FILE
sed -i "s#<WEBSERVICE_REMOTE_READ_TIMEOUT>#${WEBSERVICE_REMOTE_READ_TIMEOUT}#" $CONFIG_FILE
sed -i "s#<WEBSERVICE_REMOTE_CONNECT_TIMEOUT>#${WEBSERVICE_REMOTE_CONNECT_TIMEOUT}#" $CONFIG_FILE
sed -i "s#<WEBSERVICE_DEFAULT_PAGE_COUNT>#${WEBSERVICE_DEFAULT_PAGE_COUNT}#" $CONFIG_FILE
sed -i "s#<FHIR_INIT_BUNDLE>#${FHIR_INIT_BUNDLE}#" $CONFIG_FILE
sed -i "s#<USER_THUMBPRINTS>#${USER_THUMBPRINTS}#" $CONFIG_FILE

# Invoke base image start script
./dsf_fhir_start.sh
